# Default configuration for audio codec evaluation

device: auto  # "auto", "cuda", "cpu"
n_processes: 4  # Number of parallel processes for evaluation

metrics:
  # Signal-based metrics (fast, no model loading required)
  stoi:
    enabled: false
    extended: false  # Set to true for ESTOI
  
  pesq_nb:
    enabled: false
    
  pesq_wb:
    enabled: false

  mcd:
    enabled: true
    mcep_dim: null      # Auto-select based on sample rate
    mcep_alpha: null    # Auto-select based on sample rate  
    fft_length: 1024
    frame_shift_ms: 5
    f0_min: 80
    f0_max: 400
  
  # Model-based metrics (slower, require model loading)
  speaker_similarity:
    enabled: false
    model_name: wavlm_large  # Options: ecapa_tdnn, hubert_large, wav2vec2_xlsr, unispeech_sat, wavlm_base_plus, wavlm_large
    
  utmos:
    enabled: false
    model_name: utmos22_strong  # UTMOS model variant
    
  nisqa:
    enabled: false
    sample_rate: 16000
    
  dnsmos:
    enabled: false
    sample_rate: 16000
    personalized: false
    
  # ASR-based metrics (require transcriptions)
  wer:
    enabled: false
    model_name: openai/whisper-large-v3  # Whisper model for ASR
    language: en  # Auto-detect language, or specify (e.g., "en", "fr")